### ISSUE TITLE
找不到r2gcmn_mimic-cxr.pth文件

### ISSUE THREAD

**Issue by wang-qitong** [zhaozh10/ChatCAD#11]
如题，我并没有在Google Drive中找到对应的模型文件，请问我应该到哪里获取呢？谢谢！

**Comment by ZZH1010101010** [comment]
你好，请问你找到这个文件了吗

**Comment by 2279915269** [comment]
> 你好，请问你找到这个文件了吗

找到了，https://drive.google.com/file/d/1GdryTCibz1UPahseyN79rtVK_HjIy1Nn/view 从这个链接下载后将其重命名为r2gcmn_mimic-cxr.pth即可！

**Comment by ZZH1010101010** [comment]
感谢

**Comment by ZZH1010101010** [comment]
你好，能再问一下这篇文章你有成功复现吗，除了在Usage里面提到的那些需要下载的东西之外，还需要下载其他东西吗，我现在在输入api时一直不成功

**Comment by zhaozh10** [comment]
> 你好，能再问一下这篇文章你有成功复现吗，除了在Usage里面提到的那些需要下载的东西之外，还需要下载其他东西吗，我现在在输入api时一直不成功

这个repo主要展示了ChatCAD作为一个应用的用户UI，如仅需实现report generation，可参考 [此处](https://github.com/zhaozh10/LLM_CMP/) 里的chatcad_eval.py。首先离线生成PCAM和R2GenCMN的text prompt，随后输入LLM来生成一个综合的报告。该script中可调用其他无需网络连接的LLM进行推理。

**Comment by wang-qitong** [comment]
> > 你好，能再问一下这篇文章你有成功复现吗，除了在Usage里面提到的那些需要下载的东西之外，还需要下载其他东西吗，我现在在输入api时一直不成功
> 
> 这个repo主要展示了ChatCAD作为一个应用的用户UI，如仅需实现report generation，可参考 [此处](https://github.com/zhaozh10/LLM_CMP/) 里的chatcad_eval.py。首先离线生成PCAM和R2GenCMN的text prompt，随后输入LLM来生成一个综合的报告。该script中可调用其他无需网络连接的LLM进行推理。

omg！这个llm_cmp和直接更改chatbot调用llama所实现的功能一样吗

**Comment by zhaozh10** [comment]
> > > 你好，能再问一下这篇文章你有成功复现吗，除了在Usage里面提到的那些需要下载的东西之外，还需要下载其他东西吗，我现在在输入api时一直不成功
> > 
> > 
> > 这个repo主要展示了ChatCAD作为一个应用的用户UI，如仅需实现report generation，可参考 [此处](https://github.com/zhaozh10/LLM_CMP/) 里的chatcad_eval.py。首先离线生成PCAM和R2GenCMN的text prompt，随后输入LLM来生成一个综合的报告。该script中可调用其他无需网络连接的LLM进行推理。
> 
> omg！这个llm_cmp和直接更改chatbot调用llama所实现的功能一样吗

LLM_CMP中仅包含了``综合考量CAD网络的结果进行report generation''的功能，没有实现问答功能。若需要问答功能, 请自行将该repo中对应的prompt design移植到LLM_CMP中。由于**本工作没有对LLM进行任何训练**，因此只需采取同样的prompt design即可复现

**Comment by wang-qitong** [comment]
> > > > 你好，能再问一下这篇文章你有成功复现吗，除了在Usage里面提到的那些需要下载的东西之外，还需要下载其他东西吗，我现在在输入api时一直不成功
> > > 
> > > 
> > > 这个repo主要展示了ChatCAD作为一个应用的用户UI，如仅需实现report generation，可参考 [此处](https://github.com/zhaozh10/LLM_CMP/) 里的chatcad_eval.py。首先离线生成PCAM和R2GenCMN的text prompt，随后输入LLM来生成一个综合的报告。该script中可调用其他无需网络连接的LLM进行推理。
> > 
> > 
> > omg！这个llm_cmp和直接更改chatbot调用llama所实现的功能一样吗
> 
> LLM_CMP中仅包含了``综合考量CAD网络的结果进行report generation''的功能，没有实现问答功能。若需要问答功能, 请自行将该repo中对应的prompt design移植到LLM_CMP中。由于**本工作没有对LLM进行任何训练**，因此只需采取同样的prompt design即可复现

感谢！但是我还想问一个问题，我看到您的代码中写“牙齿x光暂未开源“，那么knee MRI是否可以被ChatCAD识别并生成报告？

**Comment by ZZH1010101010** [comment]
> > > 你好，能再问一下这篇文章你有成功复现吗，除了在Usage里面提到的那些需要下载的东西之外，还需要下载其他东西吗，我现在在输入api时一直不成功
> > 
> > 
> > 这个repo主要展示了ChatCAD作为一个应用的用户UI，如仅需实现report generation，可参考 [此处](https://github.com/zhaozh10/LLM_CMP/) 里的chatcad_eval.py。首先离线生成PCAM和R2GenCMN的text prompt，随后输入LLM来生成一个综合的报告。该script中可调用其他无需网络连接的LLM进行推理。
> 
> omg！这个llm_cmp和直接更改chatbot调用llama所实现的功能一样吗

你好，你能发一下更改chatbot调用llama的代码吗

**Comment by wang-qitong** [comment]
> > > > 你好，能再问一下这篇文章你有成功复现吗，除了在Usage里面提到的那些需要下载的东西之外，还需要下载其他东西吗，我现在在输入api时一直不成功
> > > 
> > > 
> > > 这个repo主要展示了ChatCAD作为一个应用的用户UI，如仅需实现report generation，可参考 [此处](https://github.com/zhaozh10/LLM_CMP/) 里的chatcad_eval.py。首先离线生成PCAM和R2GenCMN的text prompt，随后输入LLM来生成一个综合的报告。该script中可调用其他无需网络连接的LLM进行推理。
> > 
> > 
> > omg！这个llm_cmp和直接更改chatbot调用llama所实现的功能一样吗
> 
> 你好，你能发一下更改chatbot调用llama的代码吗

你加一下我的vx吧“a2279915269”，我把文件发给你
