### ISSUE TITLE
那个模型

### ISSUE THREAD

**Issue by doudou-itachi** [zhaozh10/ChatCAD#3]
您好 使用的那个模型

**Comment by zhaozh10** [comment]
胸片的诊断分类模型来自 [jfhealthcare](https://github.com/jfhealthcare/Chexpert)
胸片的报告生成模型来自 [R2GenCMN](https://github.com/zhjohnchan/R2GenCMN)

**Comment by Andyfever123** [comment]
Your work is impressive and has greatly inspired my research. How can I fine-tune your code using my own dataset, or how can I reproduce your paper from scratch?
