### ISSUE TITLE
您好，请问这个问题您在操作中有遇到吗，linux服务器和windows不同网络下都遇到了这个问题

### ISSUE THREAD

**Issue by DDing666** [zhaozh10/ChatCAD#5]
![Snipaste_2023-09-15_09-36-31](https://github.com/zhaozh10/ChatCAD/assets/54842941/c012a3e1-c881-4795-9c7b-1aeac7ec157b)

**Comment by zhaozh10** [comment]
请务必保持gradio==3.31.0，除此之外并没有碰到web打不开的情况
